name: Auto-Merge Single File PRs with Limits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Ensures we have at least the last two commits for diffing

      - name: Verify PR only deletes one file inside /files/
        run: |
          FILES_DELETED=$(git diff --diff-filter=D --name-only HEAD^ HEAD | grep '^files/' | wc -l)
          FILES_OUTSIDE=$(git diff --diff-filter=D --name-only HEAD^ HEAD | grep -v '^files/' | wc -l)
          if [ "$FILES_DELETED" -ne 1 ]; then
            echo "Error: Your PR must delete exactly one file inside /files/ directory."
            exit 1
          fi
          if [ "$FILES_OUTSIDE" -gt 0 ]; then
            echo "Error: You cannot delete files outside the /files/ directory."
            exit 1
          fi

      - name: Ensure PR does not add or modify files
        run: |
          ADDED_FILES=$(git diff --diff-filter=A --name-only HEAD^ HEAD | wc -l)
          MODIFIED_FILES=$(git diff --diff-filter=M --name-only HEAD^ HEAD | wc -l)
          if [ "$ADDED_FILES" -gt 0 ] || [ "$MODIFIED_FILES" -gt 0 ]; then
            echo "Error: Your PR cannot add or modify files. Only deletions are allowed."
            exit 1
          fi

      - name: Approve PR (with Debugging)
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews" \
            -d '{"event":"APPROVE"}')
          cat response.json
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Error: Failed to approve PR. GitHub API response:"
            cat response.json
            exit 1
          fi

      - name: Merge PR using GitHub API
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          curl -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/merge" \
            -d '{"merge_method":"squash"}'

      - name: Comment Encouragement Message
        run: |
          COMMENT_BODY="Nice work @${{ github.event.pull_request.user.login }}! You've successfully removed a file. Keep chiseling away! 🛠️"
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
            -d "{\"body\": \"$COMMENT_BODY\"}"
